//! Report generation — Coverage HTML + crash JSON persistence + GitHub Actions CI template.
//! Generates self-contained HTML with embedded CSS (no external dependencies).

use krastor_fuzz_core::{CoverageBitmap, FuzzActionSequence};
use krastor_fuzz_core::crash::CrashRecord;
use std::path::Path;

/// Generate a self-contained HTML coverage report.
pub fn generate_html_report(
    coverage: &CoverageBitmap,
    crashes: &[CrashRecord],
    total_rounds: u64,
    program_name: &str,
) -> String {
    let coverage_pct = if coverage.edges.len() > 0 {
        (coverage.covered_edges as f64 / coverage.edges.len() as f64) * 100.0
    } else { 0.0 };

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Krastor Report — {name}</title>
<style>
  :root {{ --bg:#0f172a; --card:#1e293b; --text:#e2e8f0; --muted:#94a3b8; --accent:#3b82f6; --red:#ef4444; --green:#22c55e; --amber:#f59e0b; }}
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ background:var(--bg); color:var(--text); font-family:system-ui,sans-serif; padding:2rem; }}
  .header {{ margin-bottom:2rem; }}
  .header h1 {{ font-size:2rem; color:var(--accent); }}
  .header .meta {{ color:var(--muted); font-size:0.875rem; }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(200px,1fr)); gap:1rem; margin-bottom:2rem; }}
  .card {{ background:var(--card); border-radius:0.5rem; padding:1.5rem; }}
  .card .label {{ color:var(--muted); font-size:0.75rem; text-transform:uppercase; letter-spacing:0.05em; }}
  .card .value {{ font-size:2rem; font-weight:700; margin-top:0.5rem; }}
  .coverage-bar {{ height:2rem; background:var(--card); border-radius:0.25rem; overflow:hidden; margin:1rem 0; }}
  .coverage-fill {{ height:100%; background:linear-gradient(90deg,var(--green),var(--accent)); transition:width 0.3s; }}
  .crashes {{ margin-top:2rem; }}
  .crash-item {{ background:var(--card); border-radius:0.5rem; padding:1rem; margin-bottom:0.5rem; border-left:3px solid var(--red); }}
  .crash-item.invariant {{ border-left-color:var(--amber); }}
  .crash-type {{ font-size:0.75rem; color:var(--muted); text-transform:uppercase; }}
  .crash-desc {{ margin-top:0.25rem; }}
  .crash-len {{ color:var(--muted); font-size:0.75rem; }}
  footer {{ margin-top:3rem; padding-top:1rem; border-top:1px solid var(--card); color:var(--muted); font-size:0.75rem; }}
</style>
</head>
<body>
  <div class="header">
    <h1>Krastor Fuzz Report</h1>
    <div class="meta">Program: {name} · Generated: {date}</div>
  </div>

  <div class="grid">
    <div class="card">
      <div class="label">Coverage</div>
      <div class="value">{coverage:.1}%</div>
    </div>
    <div class="card">
      <div class="label">Edges Covered</div>
      <div class="value">{edges}</div>
    </div>
    <div class="card">
      <div class="label">Total Rounds</div>
      <div class="value">{rounds}</div>
    </div>
    <div class="card">
      <div class="label">Crashes Found</div>
      <div class="value">{crash_count}</div>
    </div>
  </div>

  <div class="coverage-bar">
    <div class="coverage-fill" style="width:{coverage:.1}%"></div>
  </div>

  <div class="crashes">
    <h2>Crashes & Invariant Violations</h2>
    {crash_list}
  </div>

  <footer>Generated by Krastor · arielzsh/shipkit</footer>
</body>
</html>"#,
        name = program_name,
        date = chrono::Utc::now().format("%Y-%m-%d %H:%M UTC"),
        coverage = coverage_pct,
        edges = coverage.covered_edges,
        rounds = total_rounds,
        crash_count = crashes.len(),
        crash_list = crashes.iter().enumerate().map(|(i, c)| format!(
            r#"<div class="crash-item{}"><div class="crash-type">{}</div><div class="crash-desc">{}</div><div class="crash-len">Round {} · {} instr ({} removed)</div></div>"#,
            if matches!(c.crash_type, krastor_fuzz_core::crash::CrashType::InvariantViolation(_)) { " invariant" } else { "" },
            c.crash_type,
            c.description,
            c.discovered_at_round,
            c.minimal_sequence.actions.len(),
            c.instructions_removed,
        )).collect::<Vec<_>>().join("\n"),
    )
}

// UNCERTAINTY: chrono crate needed. Add to Cargo.toml: chrono = { version = "0.4", features = ["serde"] }
extern crate chrono;

/// Generate GitHub Actions CI workflow template for continuous fuzzing.
pub fn generate_github_actions_template(program_name: &str, iterations: u64) -> String {
    format!(
        r#"name: Krastor Fuzz

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: Install Krastor
        run: cargo install cargo-krastor
      - name: Build program
        run: anchor build
      - name: Run fuzz
        run: krastor fuzz run --iterations {iterations} --output coverage.html
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: krastor-coverage
          path: coverage.html
      - name: Upload crash reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: krastor-crashes
          path: crashes/
"#,
        iterations = iterations,
    )
}

/// Save a crash record to the crashes/ directory.
pub fn persist_crash(crash: &CrashRecord, output_dir: &Path) -> anyhow::Result<()> {
    std::fs::create_dir_all(output_dir)?;
    let filename = format!(
        "crash_{}_{}.json",
        crash.crash_type.to_string().to_lowercase().replace('(', "_").replace(')', ""),
        crash.discovered_at_round,
    );
    crash.save(&output_dir.join(filename))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use krastor_fuzz_core::CoverageBitmap;
    use krastor_fuzz_core::crash::{CrashRecord, CrashType};
    use krastor_fuzz_core::FuzzActionSequence;

    #[test]
    fn test_generate_html_report() {
        let cov = CoverageBitmap { edges: vec![1u8; 1000], covered_edges: 500 };
        let crashes = vec![
            CrashRecord {
                original_sequence: FuzzActionSequence { actions: vec![], initial_accounts: vec![] },
                minimal_sequence: FuzzActionSequence { actions: vec![], initial_accounts: vec![] },
                description: "test crash".into(),
                crash_type: CrashType::ExecutionError,
                discovered_at_round: 42,
                timestamp: "2026-01-01T00:00:00Z".into(),
                instructions_removed: 5,
            }
        ];

        let html = generate_html_report(&cov, &crashes, 10000, "test_prog");
        assert!(html.contains("test_prog"));
        assert!(html.contains("coverage"));
        assert!(html.contains("ExecutionError"));
        assert!(html.contains("Krastor"));
    }

    #[test]
    fn test_github_actions_template() {
        let tmpl = generate_github_actions_template("my_prog", 50000);
        assert!(tmpl.contains("krastor fuzz"));
        assert!(tmpl.contains("my_prog"));
        assert!(tmpl.contains("50000"));
        assert!(tmpl.contains("upload-artifact"));
    }
}